### ISSUE TITLE
Vivaldi browser 6.5.3206.39 incompatibility 

### ISSUE THREAD

**Issue by Alickop** [RabbyHub/Rabby#1923] opened 2023-12-15 10:36 UTC
After latest Vivaldi browser update Rabby wallet lost the ability to connect to  Web3 DApps.

When I push "connect wallet" on any DApp even Debank I got message: 
"Request Canceled 
You canceled the request."
The Rabby wallet window doesn't even open.

I checked the problem and it repeats on a clean isolated version of the browser.

**Comment by vvvvvv1vvvvvv** [comment] 2023-12-16 04:55
Can't reproduce in my side? Can you provide more info?
1. Which system you use?
2. Your browser version? 6.5.3206.39 (Stable channel) (arm64)  in my side and works fine
3. Can you please provide a screen record video?

**Comment by Alickop** [comment] 2023-12-16 10:13
1) Windows 10, x86
2) 6.5.3206.39 (Stable channel)
3)
[recording.webm](https://github.com/RabbyHub/Rabby/assets/25677031/5a402448-a13a-4e71-a8f9-91f3292ca85f)

**Comment by vvvvvv1vvvvvv** [comment] 2023-12-17 03:52
fixed in https://github.com/RabbyHub/Rabby/pull/1928

**Comment by vvvvvv1vvvvvv** [comment] 2023-12-18 05:59
fixed in 0.92.42

**Closed by vvvvvv1vvvvvv** 2023-12-18 05:59 UTC
