### ISSUE TITLE
Rabby only connects once if the browser isn't maximized

### ISSUE THREAD

**Issue by bradbrown-llc** [RabbyHub/Rabby#2150] opened 2024-03-27 07:18 UTC
Tested with 
- Rabby version 0.92.59
- Brave Browser version 1.64.109 Chromium: 123.0.6312.58 (Official Build) (64-bit)
- also with Chrome version 123.0.6312.60 (Official Build) (64-bit)

The rejection reason for the eth_requestAccounts call when the Rabby extension flashes and disappears on subsequent connection attempts is "Code 4001, User rejected the request".

Disconnecting and reconnecting work fine, only if the browser is maximized.

![image](https://github.com/RabbyHub/Rabby/assets/108493071/120643a5-87f1-4011-9f23-7ae01aa523f4)

https://github.com/RabbyHub/Rabby/assets/108493071/2894f3fb-2fc9-4cb6-8f7e-fa12b58df0c6

**Comment by vvvvvv1vvvvvv** [comment] 2024-03-27 09:03
May I ask for the system you using?
I can't reproduce it on Mac with Chrome 123.0.6312.59, will be better if you can provide your userAgent

**Comment by coffee-git** [comment] 2024-03-27 13:45
Same, happens very often. Refreshing page and reconnect doesn't help, but i havent tried to maximize window.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by bradbrown-llc** [comment] 2024-03-27 16:48
> May I ask for the system you using(Mac/Linux/Window)? I can't reproduce it on Mac with Chrome 123.0.6312.59, will be better if you can provide your userAgent

Windows 11
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

**Comment by vvvvvv1vvvvvv** [comment] 2024-03-28 02:13
reproduced, will fix soon

**Comment by vvvvvv1vvvvvv** [comment] 2024-03-28 06:21
closed since #2151 is merged

**Closed by vvvvvv1vvvvvv** 2024-03-28 06:21 UTC
Labels: bug
