### ISSUE TITLE
timeout calling estimateGas on Polygon zkEVM using Rabby

### ISSUE THREAD

**Issue by omnifient** [RabbyHub/Rabby#2048] opened 2024-02-14 10:29 UTC
Hi team, strange behaviour.

When using rabby, and making a call to estimateGas, it fails with `http2: timeout awaiting response headers`. 
The same call works with Metamask, as well as with a local script.

This points to an incompatibility between Rabby and Polygon zkEVM - reaching out to you as this is mainly happening when using Rabby.

**Comment by coreycaplan3** [comment] 2024-02-19 21:30
Just wanted to 👍 this. We're seeing users face this issue on Dolomite!

**Comment by vvvvvv1vvvvvv** [comment] 2024-02-22 03:51
How can I reproduce your issue?
Can you try to copy curl directly here?

**Comment by coreycaplan3** [comment] 2024-02-22 06:14
> How can I reproduce your issue? Can you try to copy curl directly here?

You can reproduce it by doing the following:
* Visit `app.dolomite.io` 
* Select Polygon zkEVM network on the top toolbar
* Press the `Swap` button on the Balances page to swap an asset you have deposited. I chose ETH --> MATIC
* Attempt to submit the Swap and you can see the network request that fails as well as the error logged to the console, as shown below:
![image](https://github.com/RabbyHub/Rabby/assets/13280244/8522284d-da5d-4ff9-9072-684d8fc855d8)
* Key thing is that all gas estimation calls fail

**Comment by vvvvvv1vvvvvv** [comment] 2024-02-22 07:27
> > How can I reproduce your issue? Can you try to copy curl directly here?
> 
> You can reproduce it by doing the following:
> 
> * Visit `app.dolomite.io`
> * Select Polygon zkEVM network on the top toolbar
> * Press the `Swap` button on the Balances page to swap an asset you have deposited. I chose ETH --> MATIC
> * Attempt to submit the Swap and you can see the network request that fails as well as the error logged to the console, as shown below:
>   ![image](https://private-user-images.githubusercontent.com/13280244/306884638-8522284d-da5d-4ff9-9072-684d8fc855d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODY3NzgsIm5iZiI6MTcwODU4NjQ3OCwicGF0aCI6Ii8xMzI4MDI0NC8zMDY4ODQ2MzgtODUyMjI4NGQtZGE1ZC00ZmY5LTkwNzItNjg0ZDhmYzg1NWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA3MjExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTJiNDYwOTBiYzZmZTBlNjYyZTFiODZhZjkxY2MyYTZjYjIzYjEzYmNjN2ZjMWVlNmM3ZWY3ZmE4NjFhYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLbid6YzF6ysXG2FBpnhU67zrumDIAQRc6_2Fe5MtmI)
> * Key thing is that all gas estimation calls fail

<img width="992" alt="image" src="https://github.com/RabbyHub/Rabby/assets/86296331/0a0abf67-83f8-490a-a4eb-8c6062d68720">
This works in my side

**Comment by coreycaplan3** [comment] 2024-02-22 07:30
The site sets a default gas limit if it fails. You'll need to check the dev console while submitting to see if it works or not (like in the screen shot I shared)

> > > How can I reproduce your issue? Can you try to copy curl directly here?
> > 
> > 
> > You can reproduce it by doing the following:
> > 
> > * Visit `app.dolomite.io`
> > * Select Polygon zkEVM network on the top toolbar
> > * Press the `Swap` button on the Balances page to swap an asset you have deposited. I chose ETH --> MATIC
> > * Attempt to submit the Swap and you can see the network request that fails as well as the error logged to the console, as shown below:
> >   ![image](https://private-user-images.githubusercontent.com/13280244/306884638-8522284d-da5d-4ff9-9072-684d8fc855d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODY3NzgsIm5iZiI6MTcwODU4NjQ3OCwicGF0aCI6Ii8xMzI4MDI0NC8zMDY4ODQ2MzgtODUyMjI4NGQtZGE1ZC00ZmY5LTkwNzItNjg0ZDhmYzg1NWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA3MjExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTJiNDYwOTBiYzZmZTBlNjYyZTFiODZhZjkxY2MyYTZjYjIzYjEzYmNjN2ZjMWVlNmM3ZWY3ZmE4NjFhYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MLbid6YzF6ysXG2FBpnhU67zrumDIAQRc6_2Fe5MtmI)
> > * Key thing is that all gas estimation calls fail
> 
> <img alt="image" width="992" src="https://private-user-images.githubusercontent.com/86296331/306904699-0a0abf67-83f8-490a-a4eb-8c6062d68720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODcxNzcsIm5iZiI6MTcwODU4Njg3NywicGF0aCI6Ii84NjI5NjMzMS8zMDY5MDQ2OTktMGEwYWJmNjctODNmOC00OTBhLWE0ZWItOGM2MDYyZDY4NzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDA3Mjc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMTZkZmU5OTg3MjYzMjM2ZjFiNDU1MjJiNWZhN2JkNGFjNWM1OTFjOWNiZGFjOGJmNDNhODM5Y2NiMTc0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qDw4L2EepVQWOMvmxAqgwPjDh8aZM0XlEMDoOjrBthg"> This works in my side

**Comment by vvvvvv1vvvvvv** [comment] 2024-02-22 07:34
reproduced, thanks

**Comment by vvvvvv1vvvvvv** [comment] 2024-02-22 07:52
should be fixed now

**Comment by coreycaplan3** [comment] 2024-02-22 07:55
> should be fixed now

![image](https://github.com/RabbyHub/Rabby/assets/13280244/e5ec263e-bccf-4fcb-80db-691e053588eb)

I'm getting this error now when testing

**Comment by vvvvvv1vvvvvv** [comment] 2024-02-22 08:25
I tried other rpc but no one works with this call

**Comment by omnifient** [comment] 2024-02-22 10:17
we're almost there

![image](https://github.com/RabbyHub/Rabby/assets/90161786/7bc9614d-2bcf-411e-beef-0f32d6d6e668)

this is what I got

**Comment by omnifient** [comment] 2024-03-04 09:52
hi @vvvvvv1vvvvvv any thoughts on this?

**Comment by coreycaplan3** [comment] 2024-03-06 18:36
@vvvvvv1vvvvvv bumping this as well!

**Comment by vvvvvv1vvvvvv** [comment] 2024-03-20 02:33
should be fixed soon with our self-host rpc endpoint, this timeout caused by calling remote rpc endpoint

**Closed** 2024-09-12 02:09 UTC
