### ISSUE TITLE
Signing doesn't work with BitBox02 \w optional pass

### ISSUE THREAD

**Issue by stas** [RabbyHub/Rabby#1026] opened 2022-10-09 18:59 UTC
Hi,
although I've been testing this with BitBox02, I wonder if other hardware wallets are working with Rabby.

Using Rabby to sign transactions fails on basic operations.
Eg. try to approve a token.

1. Go to, say, USDC contract: https://optimistic.etherscan.io/token/0x7f5c764cbc14f9669b88837ca1490cca17c31607
2. Connect your Rabby successfully
3. Chose the `approve()` method
4. Fill in with `0x7f5c764cbc14f9669b88837ca1490cca17c31607` and `0` (let USDC approved for USDC contract up to 0 tokens)
5. Click **Write** and watch it fail with an error like
>  Error: Unknown address { "originalError": { "message": "Error: Unknown address", "stack": "Error: Error: Unknown address\n at R.ethSendTransaction (chrome-extension://acmacodkjbdgmoleebolmdjonilkdbch/background.js:2:13522971)" } }

The data sent by the wallet is:
```json
{
    "chainId": 10,
    "data": "0x095ea7b30000000000000000000000007f5c764cbc14f9669b88837ca1490cca17c316070000000000000000000000000000000000000000000000000000000000000000",
    "from": "0x<MY_ADDRESS>",
    "gas": "0x102be",
    "gasPrice": "0xf4240",
    "nonce": "0x0",
    "to": "0x7f5c764cbc14f9669b88837ca1490cca17c31607"
}
```

/cc @benma

**Comment by benma** [comment] 2022-10-10 07:38
I tested this and it worked as expected without any errors. Used Rabby 0.50.1.

**Comment by stas** [comment] 2022-10-10 09:00
@benma I'm on chromium on linux. Latest bridge version as well. Any idea why this could be returning an error?

**Comment by stas** [comment] 2022-10-10 09:12
@benma sorry, missed one more step, I'm using an optional password on BitBox02. Can confirm that everything works without it, but still fails for me when using that.

**Comment by benma** [comment] 2022-10-10 09:14
@stas good hint - any new passphrase derives a new wallet. You might have originally setup the address on Rabby with passphrase A (or not passphrase) and now are using passphrase B. The address derived with passphrase B will not match the already setup address.

To fix, use the original passphrase (or none if if you didn't use any) or add the BitBox02 again to Rabby with passphrase B.

See also: https://shiftcrypto.support/help/en-us/21-optional-passphrase

**Comment by benma** [comment] 2022-10-10 09:16
@vvvvvv1vvvvvv maybe something to improve in Rabby in general - add a good error message when the unlocked wallet does not match a registered address - as most/all keystores have the passphrase feature.

**Comment by stas** [comment] 2022-10-10 14:59
> To fix, use the original passphrase (or none if if you didn't use any) or add the BitBox02 again to Rabby with passphrase B.

Tried again and it doesn't work. Managed to import my wallet, I can see the balance, but can't sign anything. Same error.

**Comment by benma** [comment] 2022-10-10 17:40
Maybe you still have etherscan connected to your previous address and need to reconnect / activate the new one?

Maybe try setting up Rabby from zero in a new user profile.

**Comment by stas** [comment] 2022-10-11 14:21
@benma I can't make it work. Once again steps to reproduce:

 1. Set up BitBox02 to use an optional password
 2. Connect and unlock
 3. Open Rabby and import your wallet from a non-zero index (not the first/default wallet)
 4. Try to sign any transaction

**Comment by jadzeidan** [comment] 2022-10-14 10:43
@stas I reproduced your steps and it seemed to work for me.

I added multiple BB02 wallets to Rabby. I added an account that used a passphrase and was not the first account of the wallet. I was able to successfully make a tx from that account. 

Note that at first I wasn't able to send, I could sign the tx on the BB02 but then nothing would happen (Rabby would still be on the "send" screen"). And I got no error when this happened. However just restarting chrome fixed the issue, so maybe it is unrelated.

**Comment by stas** [comment] 2022-10-14 11:17
Thanks @jadzeidan will try to debug this a bit more, very weird. :heart:

**Comment by stas** [comment] 2022-10-14 11:32
@jadzeidan @benma try the wallet at index 1000. It worked with lower index wallets, say 100 though. Please confirm I'm not tripping :see_no_evil: :pray:

**Comment by vvvvvv1vvvvvv** [comment] 2022-10-14 12:01
> @vvvvvv1vvvvvv maybe something to improve in Rabby in general - add a good error message when the unlocked wallet does not match a registered address - as most/all keystores have the passphrase feature.

Yes, we are having a try on Ledger currently, will considerate to spread to other hardware wallet soon

**Comment by benma** [comment] 2022-10-14 12:32
@stas well that explains it. 99 is the maximum allowed index (for a total of 100 accounts):

https://github.com/RabbyHub/Rabby/blob/779db7bc7f8bf1fe27406d4ef440a9b73a9501b9/src/background/service/keyring/eth-bitbox02-keyring.ts#L21

https://github.com/RabbyHub/Rabby/blob/779db7bc7f8bf1fe27406d4ef440a9b73a9501b9/src/background/service/keyring/eth-bitbox02-keyring.ts#L338-L348

Do you really need over a hundred accounts, or how come that you are trying such high indices?

I guess the error message is not very clear there.

**Comment by stas** [comment] 2022-10-14 13:24
> Do you really need over a hundred accounts, or how come that you are trying such high indices?

Got it accidentally setup like this, not a big deal, but just wanted to figure out why things do not work. Now it makes sense.... 

Thanks again for helping figure it out!

**Comment by benma** [comment] 2022-10-14 14:07
Cool. I guess you can close the issue then.

**Comment by stas** [comment] 2022-10-14 14:31
Leave it up to you guys if you want to update the message and `MAX_INDEX`, can prepare a PR. If not, indeed can be closed.

**Comment by benma** [comment] 2022-10-14 15:05
Would be great if you could make a PR improving the message.

**Closed** 2022-11-03 02:18 UTC

**Comment by vvvvvv1vvvvvv** [comment] 2022-11-07 04:09
> Hey guys, appreciate if next time you just clarify that some issue/PR is not relevant to the project so that contributions are not ignored/wasted.
> 
> As for the issue, I can see you decided Rabby should just ignore any accounts which are beyond 100th index... Leaving this here for other folks in case they bump into the same problem...

It's not our decision, this limitation is also in bitbox02 firmware https://github.com/digitalbitbox/bitbox02-firmware/blob/master/src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs#L21 so you can't import beyond 100th even Rabby allow it

**Comment by stas** [comment] 2022-11-07 10:53
> It's not our decision, this limitation is also in bitbox02 firmware https://github.com/digitalbitbox/bitbox02-firmware/blob/master/src/rust/bitbox02-rust/src/hww/api/ethereum/keypath.rs#L21 so you can't import beyond 100th even Rabby allow it

Hmm, thanks, but this is still very confusing, because I can 100% confirm I have the wallet imported and it was beyond 100th index.
Either way, this is no longer relevant as things are merged.

**Comment by jadzeidan** [comment] 2022-11-07 11:07
@stas could you please check again? It would be surprising to us if you could have an account beyond the 100 limit. The limit is there as a security feature so coins aren't accidently lost due to them being in an account that is beyond a reasonable scanning range.
